name: ğŸš€ CI Pipeline ; Streamlit & MLFlow Project

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: ğŸ§¾ Checkout Repository
        uses: actions/checkout@v3

      # Set up Python
      - name: ğŸ Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # Move to the Notebook directory
      - name: ğŸ“‚ Navigate to Notebooks Folder
        working-directory: ./Notebooks
        run: echo "Switched to Notebooks directory"

      # Install dependencies
      - name: ğŸ“¦ Install Dependencies
        working-directory: ./Notebooks
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run tests (Pytest)
      - name: ğŸ§ª Run Unit Tests
        working-directory: ./Notebooks
        run: pytest Test_Training.py --maxfail=1 --disable-warnings -q

      # Build Docker image
      - name: ğŸ³ Build Docker Image
        working-directory: ./Notebooks
        run: docker build -t bike-prediction-app .

    
